name: Self Hosted Runner Test

on:
  workflow_dispatch: # this workflow will run manually from GitHub; Run workflow button will be there to run the workflow

jobs:
  test-self-hosted-runner:
    runs-on: self-hosted

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    steps:
      - name: Test Runner
        run: | # | pipe sign here indicates thet there are multiple commands to be run here in this specific run
          echo "Namaste from my self-hosted runner!"
          echo "Computer Name:"
          hostname
          echo "Operating System:"

      - name: check terraform version
        run: terraform version

      - name: current working directory
        run: pwd

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: check list of Files
        run: ls -Force

      - name: Initializing Cloud Provider
        working-directory: environments/pre-prod
        run: terraform init

      - name: Validating Terraform Code
        run: terraform validate

      - name: Show Plan
        working-directory: environments/pre-prod
        run: terraform plan -no-color

      - name: Apply Changes
        # if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main'
        working-directory: environments/pre-prod
        run: terraform apply --auto-approve